config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.views import AnalysisListView, DoctorListView, DoctorDetailView, AnalysisDetailView, OrderCreateView, contacts

app_name = 'main'

urlpatterns = [
    path('', AnalysisListView.as_view(), name='analysis_list'),
    path('doctors/', DoctorListView.as_view(), name='doctors_list'),
    path('doctor/<int:pk>', DoctorDetailView.as_view(), name='doctor_detail'),
    path('analysis/<int:pk>', AnalysisDetailView.as_view(), name='analysis_detail'),
    path('order/', OrderCreateView.as_view(), name='order'),
    path('contacts/', contacts, name='contacts'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import RegisterView, UserUpdateView

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
]

main/models.py
from django.db import models

from users.models import User


# Create your models here.


class Analysis(models.Model):
    title = models.CharField(max_length=150, verbose_name='Название анализа')
    description = models.TextField(verbose_name='Описание анализа')
    duration = models.PositiveIntegerField(verbose_name='Срок оказания услуги')
    price = models.PositiveIntegerField(verbose_name='Стоимость')

    class Meta:
        verbose_name = 'Анализ'
        verbose_name_plural = 'Анализы'


class Doctor(models.Model):
    photo = models.ImageField(upload_to='photo/', verbose_name='Фото', null=True, blank=True)
    full_name = models.CharField(max_length=150, verbose_name='ФИО')
    profile = models.CharField(max_length=150, verbose_name='Медицинское направление')
    experience = models.PositiveSmallIntegerField(verbose_name='Стаж работы')
    start_price = models.PositiveIntegerField(verbose_name='Стоимость приёма')

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'Врач'
        verbose_name_plural = 'Врачи'


class Order(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, verbose_name='Врач')
    consultation_date = models.DateTimeField(verbose_name='Дата записи')
    client = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Клиент')

    class Meta:
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

main/views.py
from django.forms import DateTimeInput
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView

from main.models import Analysis, Doctor, Order


class AnalysisListView(ListView):
    model = Analysis


class AnalysisDetailView(DetailView):
    model = Analysis


class DoctorListView(ListView):
    model = Doctor


class DoctorDetailView(DetailView):
    model = Doctor


class OrderCreateView(CreateView):
    model = Order
    fields = 'doctor', 'consultation_date'
    success_url = reverse_lazy('main:analysis_list')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['consultation_date'].widget = DateTimeInput(attrs={'type': 'datetime-local', 'step': 1800})
        return form


def contacts(request):
    return render(request, 'main/contacts.html')

users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from users.forms import UserRegisterForm, UserUpdateForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')


class UserUpdateView(UpdateView):
    model = User
    template_name = 'users/user_form.html'
    success_url = reverse_lazy('users:profile')
    form_class = UserUpdateForm

    def get_object(self, queryset=None):
        return self.request.user

main/templates/main/analysis_detail.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
    <div class="row text-center">

        <h1>Информация об анализе</h1>
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h2 class="my-0 font-weight-normal">{{ object.title }}</h2>
                </div>
                <div class="card-body">
                    <p>Описание: {{ object.description }}</p>
                    <p>Длительность выполнения: {{ object.duration }}</p>
                    <p>Стоимость: {{ object.price }}</p>
                    <a class="btn btn-primary" href="{% url 'main:order' %}">Запись к
                        врачу</a>

                </div>
            </div>
        </div>


    </div>
</div>
{% endblock %}

main/templates/main/analysis_list.html
{% extends 'main/base.html' %}


{% block content %}

<div class="container">
    <div class="row text-center">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Название</th>
                <th scope="col">Описание</th>
                <th scope="col">Срок выполнения</th>
                <th scope="col">Цена</th>
                <th scope="col">Ссылка</th>

            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
            <tr>
                <th scope="row">{{ object.title }}</th>
                <td>{{ object.description }}</td>
                <td>{{ object.duration }}</td>
                <td>{{ object.price }}</td>
                <td><a href="{% url 'main:analysis_detail' object.pk %}"
                       class="btn btn-lg btn-block btn-outline-primary">Открыть</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

main/templates/main/base.html
{% load static %}

<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.118.2">
    <title>Medical Company</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/pricing/">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">


    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static '/css/pricing.css' %}" rel="stylesheet">
</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>


<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check" viewBox="0 0 16 16">
        <title>Check</title>
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
</svg>

<div class="container py-3">
    <header>
        <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
            <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94"
                     role="img"><title>Medical Company</title>
                    <path fill-rule="evenodd" clip-rule="evenodd"
                          d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"
                          fill="currentColor"></path>
                </svg>
                <span class="fs-4">Medical Company</span>
            </a>
            {% include 'main/includes/top_menu.html' %}
        </div>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    {% include 'main/includes/footer.html' %}

</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

main/templates/main/contacts.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}

<div class="container">
    <div class="row text-center">
        <h1>Контакты</h1>
        <h2>Медицинская клиника на Набережной</h2>
        <p>Адрес: Ростовская набережная 1</p>
        <p>Телефон: 8-800-800-80-80</p>
        <p>Почта: info@med.ru</p>
        <img src="/media/map.png">

    </div>
</div>
{% endblock %}

main/templates/main/doctor_detail.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
    <div class="row text-center">

        <h1>Информация о докторе</h1>
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h2 class="my-0 font-weight-normal">{{ object.full_name }}</h2>
                </div>
                <div class="card-body">
                    <img src="{{ object.photo.url }}" width="100">
                    <p>Направление: {{ object.profile }}</p>
                    <p>Стаж работы: {{ object.experience }}</p>
                    <p>Стоимость консультации: {{ object.start_price }}</p>
                    <a class="btn btn-primary" href="{% url 'main:order' %}">Запись к
                        врачу</a>

                </div>
            </div>
        </div>


    </div>
</div>
{% endblock %}

main/templates/main/doctor_list.html
{% extends 'main/base.html' %}


{% block content %}

<div class="container">
    <div class="row text-center">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Фото</th>
                <th scope="col">ФИО</th>
                <th scope="col">Направление</th>
                <th scope="col">Стаж работы</th>
                <th scope="col">Стоимость консультации</th>
                <th scope="col">Ссылка</th>

            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
            <tr>
                <td>
                    {% if object.photo %}
                    <img src="{{ object.photo.url }}" width="100">
                    {% else %}
                    <img src="/media/no-avatar.jpg" width="100">
                    {% endif %}
                </td>
                <td>{{ object.full_name }}</td>
                <td>{{ object.profile }}</td>
                <td>{{ object.experience }}</td>
                <td>{{ object.start_price }}</td>
                <td><a href="{% url 'main:doctor_detail' object.pk %}"
                       class="btn btn-lg btn-block btn-outline-primary">Открыть</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

main/templates/main/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <small class="d-block mb-3 text-body-secondary">&copy; 2017–2023</small>
      </div>
      <div class="col-6 col-md">
        <h5>Функциональность</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Крутые штуки</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Случайная функция</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Командная функция</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Вещи для разработчиков</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Еще одна</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Последний раз</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Ресурсы</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Ресурс</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Название ресурса</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Еще один ресурс</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Финальный ресурс</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>О нас</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Команда</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Местоположения</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Конфиденциальность</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Условия использования</a></li>
        </ul>
      </div>
    </div>
  </footer>

main/templates/main/includes/top_menu.html
{% csrf_token %}
<nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
    <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'main:analysis_list' %}">Анализы</a>
    <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'main:doctors_list' %}">Врачи</a>
    <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'main:order' %}">Запись к врачу</a>
    <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'main:contacts' %}">Контакты</a>
    {% if user.is_authenticated %}
    <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'users:profile' %}">Профиль</a>
    <form action="{% url 'users:logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Выйти</button>
    </form>
    {% else %}
    <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'users:register' %}">Регистрация</a>
    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <button type="submit">Войти</button>
    </form>
    {% endif %}
</nav>

main/templates/main/order_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">

        <div class="card">
            <div class="card-header">
                <div class="card-title">Запись к врачу</div>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Записаться</button>
            </div>
            <div class="card-footer"></div>
        </div>

    </form>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Вход</div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Войти</button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Регистрация</div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Зарегестрироваться</button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Редактирование профиля</div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}